### ISSUE TITLE
Using in RST: Unknown interpreted text role "github".

### ISSUE THREAD

**Issue by sappelhoff** [astrojuanlu/sphinx-github-role#15]
Hi there, having seen your recent tweet I wanted to give this package (thanks for developing it!) a shot at https://github.com/autoreject/autoreject/pull/251.

I did the following:

- pip-installed `sphinx-github-role` in my doc build job
- added the following to my `conf.py`: `github_default_org_project = ("autoreject", "autoreject")`
- used the following syntax in my changelog: 

```
:github:`#225`
```

Yet, the [rendered docs](https://1041-59485140-gh.circle-artifacts.com/0/html/whats_new.html) look broken.

And the [build log](https://circleci.com/api/v1.1/project/github/autoreject/autoreject/1041/output/107/0?file=true&allocation-id=61a746205dba723eb5f5806e-0-build%2F307DBCD6) gives me an error:

> Using in RST: Unknown interpreted text role "github".

Can you see what's going wrong? Is that some user error of mine? Or something with sphinx-github-role?

**Comment by astrojuanlu** [comment]
Hey @sappelhoff , thanks for trying it out! I left a comment in the PR. I'll leave this issue open as a reminder to myself to clarify in the readme that one needs to add `sphinx_github_role` to `extensions` in the `conf.py`.

**Comment by sappelhoff** [comment]
Okay, sounds good - a little reminder certainly would have helped me. Thanks!
