### ISSUE TITLE
Support linking directly to projects without an issue

### ISSUE THREAD

**Issue by zml2008** [astrojuanlu/sphinx-github-role#17]
I'd like to use this role to be able to link directly to GitHub projects, rather than just to specific issues within the projects.

For example:

```rst
:github:`astrojuanlu/sphinx-github-role`
```

would link to this repository, without requiring an issue to be specified.

I'm documenting a project with different components across a variety of repositories, so a shorthand syntax for referencing specific repositories would be helpful.

**Comment by astrojuanlu** [comment]
Good idea @zml2008 ! Do you want to send a pull request for it?
